services:
  cleanup:
    image: postgres:18-alpine
    entrypoint: [ "sh", "/cleanup.sh" ]
    volumes:
      - ./cleanup.sh:/cleanup.sh:ro,z
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - funsplash
    restart: unless-stopped
    mem_limit: 16m
    cpus: 0.05

  funsplash:
    build:
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "1337:1337"
    env_file:
      - .env
    networks:
      - funsplash
    restart: unless-stopped
    mem_limit: 1348m
    cpus: 1.45

  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - funsplash
    mem_limit: 512m
    cpus: 0.5
    volumes:
      - postgres_data:/var/lib/postgresql:z
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql:z
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${PGUSER} -d $${PGDATABASE}" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  funsplash:
    driver: bridge

volumes:
  postgres_data:
