services:
  funsplash-checker:
    build: .
    # The checker runs a HTTP interfaces, so we need to map port 3031 to the outside (port 8000).
    ports:
      - 11337:8000
    environment:
      - MONGO_ENABLED=1
      - MONGO_HOST=funsplash-mongo
      - MONGO_PORT=27017
      - MONGO_USER=funsplash
      - MONGO_PASSWORD=funsplash
    mem_limit: 2G
    memswap_limit: 2G
    ulimits:
      core:
        soft: 0
        hard: 0
      nproc:
        soft: 4000
        hard: 4000
  # The python checkerlib requires a mongo db!
  funsplash-mongo:
    image: mongo:8
    #ports:
    #  - 27017:27017
    volumes:
      - ./data:/data/db:z
    environment:
      MONGO_INITDB_ROOT_USERNAME: funsplash
      MONGO_INITDB_ROOT_PASSWORD: funsplash
    mem_limit: 2G
    memswap_limit: 2G
    ulimits:
      core:
        soft: 0
        hard: 0
      nproc:
        soft: 4000
        hard: 4000
        
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1420
